name: Test PR Bot

on:
  workflow_dispatch:
  issue_comment:

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/ci run-pr-bot')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Produce some stdout
      run: |
        echo "CPU Usage: 45%" > output.txt
        echo "Memory Usage: 60%" >> output.txt
        echo "Disk Usage: 70%" >> output.txt

    - name: Read output
      id: read_output
      run: |
        output=$(cat output.txt | base64)
        echo "::set-output name=stdout::$output"

    - name: Create comment with results
      uses: actions/github-script@v7
      with:
        script: |
          const output = Buffer.from('${{ steps.read_output.outputs.stdout }}', 'base64').toString('utf-8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Some logged output:\n\`\`\`\n${output}\n\`\`\``
          });