name: Test PR Bot

on:
  workflow_dispatch:
  issue_comment:

jobs:
  test:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && contains(github.event.comment.body, '/ci run-pr-bot')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Produce some stdout
      run: printf "CPU Usage: 45%\nMemory Usage: 60%\nDisk Usage: 70%\n"

    - name: Create comment with results
      uses: actions/github-script@v7
      with:
        script: |
          const output = `${{ steps.test_pr_bot.outputs.stdout }}`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Some logged output:\n\`\`\`\n${output}\n\`\`\``
          });
