name: Test PR Bot

on:
  workflow_dispatch:
  issue_comment:
permissions:
  contents: read
  issues: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Add PR branch ability
      if: ${{ github.event.issue.pull_request }}
      uses: xt0rted/pull-request-comment-branch@v3
      id: comment-branch

    - uses: actions/checkout@v4
      if: ${{ github.event.issue.pull_request }}
      with:
        ref: ${{ steps.comment-branch.outputs.head_ref }}

    - run: git rev-parse --abbrev-ref HEAD
    - run: git rev-parse --verify HEAD

    - name: Show branch name
      run: git branch --show-current

    - name: Produce some stdout
      run: |
        echo "CPU Usage: 45%" > output.txt
        echo "Memory Usage: 60%" >> output.txt
        echo "Disk Usage: 70%" >> output.txt

    - name: Read output
      id: read_output
      run: |
        output=$(cat output.txt | base64 | tr -d '\n')
        echo "::set-output name=stdout::$output"

    - name: Create comment with results
      uses: actions/github-script@v7
      with:
        script: |
          const output = Buffer.from('${{ steps.read_output.outputs.stdout }}', 'base64').toString('utf-8').trim();
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `Some logged output:\n\`\`\`\n${output}\n\`\`\``
          });
